In [1]:
import numpy as np

In [12]:
arr = np.arange(1, 10)

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr / 14

array([0.07142857, 0.14285714, 0.21428571, 0.28571429, 0.35714286,
       0.42857143, 0.5       , 0.57142857, 0.64285714])

In [16]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr % 4

array([1, 2, 3, 0, 1, 2, 3, 0, 1])

In [18]:
1 / arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [19]:
# BUILT IN MATH FUNCTIONS
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [21]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [23]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr.mean()

5.0

In [26]:
arr.sum()

45

In [27]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [29]:
arr_2d.shape

(3, 4)

In [30]:
arr_2d.sum()

78

In [33]:
# Give me sum across the rows -> sum of values in the columns
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [34]:
arr_2d.sum(axis=1)

array([10, 26, 42])