In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# grab single value
arr[1]

1

In [5]:
# grab range
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [6]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
arr / 14

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571])

In [9]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
sliced_arr = arr[0:6]
sliced_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
sliced_arr[:]

array([0, 1, 2, 3, 4, 5])

In [16]:
# this is updating the original array due to pointers
sliced_arr[:] = 99

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# can create a copy here
arr_copy = arr.copy()

In [19]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
# Indexing on a 2D Array
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d.shape

(3, 3)

In [23]:
# get item from 2d array
arr_2d[1]

array([20, 25, 30])

In [24]:
arr_2d[1][1]

25

In [25]:
arr_2d[1, 1]

25

In [26]:
arr_2d[2, 2]

45

In [30]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [31]:
# CONDITIONAL SELECTION
# comparison operators in order to select partial values
arr = np.arange(1, 11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
bool_arr = arr > 4

In [35]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])